sudo: false
language: php
matrix:
  include:
  - php: 7
    env: WP_TRAVISCI=travis:js
  - php: 5.6
  - php: hhvm
    sudo: required
    dist: trusty
    group: edge
    addons:
      apt:
        packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
  - php: 7.0
  - php: nightly
  allow_failures:
  - php: hhvm
  - php: nightly

before_script:
  - composer self-update
  - composer install --dev --prefer-dist

script:
  - ./bin/behat